site_name: 科研学帮帮
theme:
  name: material 
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra_css:
  - stylesheets/extra.css

